//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM_IPS.PLFLARCCAYRClassWeb
{
	/// <summary>
	/// DomainModel PLFLARCCAYRClassWebDomainModel
	/// Description for UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWeb
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel.DisplayName", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("ced55abc-6d18-423a-8d79-f66f713f3f11")]
	public partial class PLFLARCCAYRClassWebDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// PLFLARCCAYRClassWebDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0xced55abc, 0x6d18, 0x423a, 0x8d, 0x79, 0xf6, 0x6f, 0x71, 0x3f, 0x3f, 0x11);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public PLFLARCCAYRClassWebDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(Tapiz),
				typeof(Elemento),
				typeof(Clase),
				typeof(Atributo),
				typeof(Operacion),
				typeof(Parametros),
				typeof(TapizHasClases),
				typeof(ClaseHasAtributo),
				typeof(ClaseHasOperacioned),
				typeof(OperacionHasParametro),
				typeof(PLFLARCCAYRClassWebDiagram),
				typeof(MetaforaClase),
				typeof(MetaforaOperacion),
				typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.FixUpDiagram),
				typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.CompartmentItemAddRule),
				typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.CompartmentItemDeleteRule),
				typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.CompartmentItemRolePlayerChangeRule),
				typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.CompartmentItemRolePlayerPositionChangeRule),
				typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.CompartmentItemChangeRule),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Tapiz), "nombreSolucion", Tapiz.nombreSolucionDomainPropertyId, typeof(Tapiz.nombreSolucionPropertyHandler)),
				new DomainMemberInfo(typeof(Elemento), "nombre", Elemento.nombreDomainPropertyId, typeof(Elemento.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Elemento), "tipoDato", Elemento.tipoDatoDomainPropertyId, typeof(Elemento.tipoDatoPropertyHandler)),
				new DomainMemberInfo(typeof(Elemento), "nombreTipoCalculada", Elemento.nombreTipoCalculadaDomainPropertyId, typeof(Elemento.nombreTipoCalculadaPropertyHandler)),
				new DomainMemberInfo(typeof(Clase), "nombre", Clase.nombreDomainPropertyId, typeof(Clase.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Clase), "id", Clase.idDomainPropertyId, typeof(Clase.idPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(TapizHasClases), "Tapiz", TapizHasClases.TapizDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizHasClases), "Clase", TapizHasClases.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributo), "Clase", ClaseHasAtributo.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributo), "Atributo", ClaseHasAtributo.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasOperacioned), "Clase", ClaseHasOperacioned.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasOperacioned), "Operacion", ClaseHasOperacioned.OperacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(OperacionHasParametro), "Operacion", OperacionHasParametro.OperacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(OperacionHasParametro), "Parametros", OperacionHasParametro.ParametrosDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(9);
				createElementMap.Add(typeof(Tapiz), 0);
				createElementMap.Add(typeof(Elemento), 1);
				createElementMap.Add(typeof(Clase), 2);
				createElementMap.Add(typeof(Atributo), 3);
				createElementMap.Add(typeof(Operacion), 4);
				createElementMap.Add(typeof(Parametros), 5);
				createElementMap.Add(typeof(PLFLARCCAYRClassWebDiagram), 6);
				createElementMap.Add(typeof(MetaforaClase), 7);
				createElementMap.Add(typeof(MetaforaOperacion), 8);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new Tapiz(partition, propertyAssignments);
				case 1: return new Elemento(partition, propertyAssignments);
				case 2: return new Clase(partition, propertyAssignments);
				case 3: return new Atributo(partition, propertyAssignments);
				case 4: return new Operacion(partition, propertyAssignments);
				case 5: return new Parametros(partition, propertyAssignments);
				case 6: return new PLFLARCCAYRClassWebDiagram(partition, propertyAssignments);
				case 7: return new MetaforaClase(partition, propertyAssignments);
				case 8: return new MetaforaOperacion(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(4);
				createElementLinkMap.Add(typeof(TapizHasClases), 0);
				createElementLinkMap.Add(typeof(ClaseHasAtributo), 1);
				createElementLinkMap.Add(typeof(ClaseHasOperacioned), 2);
				createElementLinkMap.Add(typeof(OperacionHasParametro), 3);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new TapizHasClases(partition, roleAssignments, propertyAssignments);
				case 1: return new ClaseHasAtributo(partition, roleAssignments, propertyAssignments);
				case 2: return new ClaseHasOperacioned(partition, roleAssignments, propertyAssignments);
				case 3: return new OperacionHasParametro(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return PLFLARCCAYRClassWebDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (PLFLARCCAYRClassWebDomainModel.resourceManager == null)
				{
					PLFLARCCAYRClassWebDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(PLFLARCCAYRClassWebDomainModel).Assembly);
				}
				return PLFLARCCAYRClassWebDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return PLFLARCCAYRClassWebDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return PLFLARCCAYRClassWebDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (PLFLARCCAYRClassWebDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new PLFLARCCAYRClassWebCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					PLFLARCCAYRClassWebDomainModel.copyClosure = copyFilter;
				}
				return PLFLARCCAYRClassWebDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (PLFLARCCAYRClassWebDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new PLFLARCCAYRClassWebDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					PLFLARCCAYRClassWebDomainModel.removeClosure = removeFilter;
				}
				return PLFLARCCAYRClassWebDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.CompartmentItemAddRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.CompartmentItemDeleteRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.CompartmentItemRolePlayerChangeRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.CompartmentItemChangeRule));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.CompartmentItemAddRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.CompartmentItemDeleteRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.CompartmentItemRolePlayerChangeRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.CompartmentItemChangeRule));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class PLFLARCCAYRClassWebDeleteClosure : PLFLARCCAYRClassWebDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public PLFLARCCAYRClassWebDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class PLFLARCCAYRClassWebDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public PLFLARCCAYRClassWebDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM_IPS.PLFLARCCAYRClassWeb.TapizHasClases.ClaseDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.PLFLARCCAYRClassWeb.ClaseHasAtributo.AtributoDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.PLFLARCCAYRClassWeb.ClaseHasOperacioned.OperacionDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.PLFLARCCAYRClassWeb.OperacionHasParametro.ParametrosDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class PLFLARCCAYRClassWebCopyClosure : PLFLARCCAYRClassWebCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public PLFLARCCAYRClassWebCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class PLFLARCCAYRClassWebCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public PLFLARCCAYRClassWebCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace UPM_IPS.PLFLARCCAYRClassWeb
{
	/// <summary>
	/// DomainEnumeration: TipoDato
	/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoDato
	{
		/// <summary>
		/// Byte
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato.Byte
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato/Byte.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		Byte = 0,
		/// <summary>
		/// Short
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato.Short
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato/Short.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		Short = 1,
		/// <summary>
		/// Int
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato.Int
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato/Int.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		Int = 3,
		/// <summary>
		/// Long
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato.Long
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato/Long.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		Long = 4,
		/// <summary>
		/// Float
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato.Float
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato/Float.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		Float = 5,
		/// <summary>
		/// Double
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato.Double
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato/Double.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		Double = 6,
		/// <summary>
		/// Char
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato.Char
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato/Char.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		Char = 7,
		/// <summary>
		/// Boolean
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato.Boolean
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato/Boolean.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		Boolean = 8,
		/// <summary>
		/// String
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato.String
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato/String.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		String = 9,
	}
}
namespace UPM_IPS.PLFLARCCAYRClassWeb
{
	/// <summary>
	/// DomainEnumeration: TipoDato1
	/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoDato1
	{
		/// <summary>
		/// Byte
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1.Byte
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1/Byte.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		Byte = 0,
		/// <summary>
		/// Short
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1.Short
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1/Short.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		Short = 1,
		/// <summary>
		/// Int
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1.Int
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1/Int.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		Int = 3,
		/// <summary>
		/// Long
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1.Long
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1/Long.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		Long = 4,
		/// <summary>
		/// Float
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1.Float
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1/Float.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		Float = 5,
		/// <summary>
		/// Double
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1.Double
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1/Double.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		Double = 6,
		/// <summary>
		/// Char
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1.Char
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1/Char.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		Char = 7,
		/// <summary>
		/// Boolean
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1.Boolean
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1/Boolean.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		Boolean = 8,
		/// <summary>
		/// String
		/// Description for UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1.String
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.PLFLARCCAYRClassWeb.TipoDato1/String.Description", typeof(global::UPM_IPS.PLFLARCCAYRClassWeb.PLFLARCCAYRClassWebDomainModel), "UPM_IPS.PLFLARCCAYRClassWeb.GeneratedCode.DomainModelResx")]
		String = 9,
	}
}

