//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.PLFLARCCAYRClassWeb
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "PLFLARCCAYR_DSLClassWeb";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"PLFLARCCAYRClassWeb";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID PLFLARCCAYRClassWebDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PLFLARCCAYRClassWebCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID PLFLARCCAYRClassWebExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PLFLARCCAYRClassWebCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewPLFLARCCAYRClassWebExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PLFLARCCAYRClassWebCommandSetId), 0x0001);
	
		// Package identifier
		public const string PLFLARCCAYRClassWebPackageId = "e5ddda47-db2a-44bd-b11f-fd632c9c19e4";
		
		// Editor factory identifier
		public const string PLFLARCCAYRClassWebEditorFactoryId = "a59eef72-a1e0-4275-b086-30b7b49fcf8d";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string PLFLARCCAYRClassWebModelExplorerToolWindowId = "8edc0750-d54a-4278-8a8b-4574b451151d";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.PLFLARCCAYRClassWeb
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string PLFLARCCAYRClassWebCommandSetId = "195da57e-7b26-4104-958c-628c25df43e3";
	}
}